#!/usr/bin/env python3
"""Train the local GRPO-style REINFORCE policy and evaluate on held-out rooms.

Fully local and seeded — no API key. Saves the trained weights and the
learning curve as JSON so the benchmark and the paper's figures can be
regenerated by anyone.

Usage:
    python3 scripts/train_local_rl.py --iters 400 --group 8 --seed 0 \
        --train-rooms 12 --test-rooms 8 --hint \
        --out weights.json --curve-out curve.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from wanderai.rl_local import RLConfig, train_and_eval  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--iters", type=int, default=400)
    ap.add_argument("--group", type=int, default=8, help="GRPO group size")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--hint", dest="hint", action="store_true", default=False,
                    help="append the agent's own frontier-map hint to features")
    ap.add_argument("--no-hint", dest="hint", action="store_false")
    ap.add_argument("--train-rooms", type=int, default=12)
    ap.add_argument("--test-rooms", type=int, default=8)
    ap.add_argument("--split-seed", type=int, default=7)
    ap.add_argument("--lr", type=float, default=3e-3)
    ap.add_argument("--max-steps", type=int, default=120,
                    help="max steps per training episode")
    ap.add_argument("--out", type=str, default=None,
                    help="path to save trained weights JSON")
    ap.add_argument("--curve-out", type=str, default=None,
                    help="path to save learning-curve JSON")
    args = ap.parse_args()

    cfg = RLConfig(iters=args.iters, group_size=args.group, lr=args.lr,
                   max_steps=args.max_steps, seed=args.seed,
                   use_hint=args.hint)
    print(f"config: {cfg}")
    print(f"rooms: train={args.train_rooms} test={args.test_rooms} "
          f"split_seed={args.split_seed}")

    def progress(it: int, stats: dict) -> None:
        if (it + 1) % 20 == 0 or it == 0:
            print(f"iter {it + 1:4d}/{args.iters}  "
                  f"mean_return {stats['mean_return']:+7.3f}  "
                  f"SR {stats['success_rate']:.2f}  "
                  f"entropy {stats['mean_entropy']:.3f}", flush=True)

    out = train_and_eval(n_train=args.train_rooms, n_test=args.test_rooms,
                         split_seed=args.split_seed, cfg=cfg, progress=progress)

    def show(tag: str, s: dict) -> None:
        print(f"{tag}: SR {s['success_rate']:.3f}  SPL {s['spl']:.3f}  "
              f"softSPL {s['soft_spl']:.3f}  DTS {s['dts']:.2f}  "
              f"mean_steps {s['mean_steps']:.1f}")

    print("\n=== held-out evaluation (max_steps=300) ===")
    show("untrained", out["eval_untrained"])
    show("trained  ", out["eval_trained"])

    if args.out:
        with open(args.out, "w") as f:
            json.dump(out["weights"], f)
        print(f"weights -> {args.out}")
    if args.curve_out:
        with open(args.curve_out, "w") as f:
            json.dump({"config": vars(args), "history": out["train_history"],
                       "eval_untrained": out["eval_untrained"],
                       "eval_trained": out["eval_trained"]}, f, indent=1)
        print(f"learning curve -> {args.curve_out}")


if __name__ == "__main__":
    main()
